// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOWQwbp8zySf1Xr840w3F41eHAn_glA6o',
    appId: '1:40178181277:web:5c0eef0991351143f66074',
    messagingSenderId: '40178181277',
    projectId: 'ttu-housing-app',
    authDomain: 'ttu-housing-app.firebaseapp.com',
    storageBucket: 'ttu-housing-app.firebasestorage.app',
    measurementId: 'G-0CNGVK8TCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA50_AMJlxrDMvsglT4t_zsVD1uEzk3wxQ',
    appId: '1:40178181277:android:99409b43b4ec44f7f66074',
    messagingSenderId: '40178181277',
    projectId: 'ttu-housing-app',
    storageBucket: 'ttu-housing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcqcg9gTxr4gsRODjBOI3iZKr8cJSVgqg',
    appId: '1:40178181277:ios:c18d1855479233f9f66074',
    messagingSenderId: '40178181277',
    projectId: 'ttu-housing-app',
    storageBucket: 'ttu-housing-app.firebasestorage.app',
    iosBundleId: 'com.example.ttuHousingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcqcg9gTxr4gsRODjBOI3iZKr8cJSVgqg',
    appId: '1:40178181277:ios:c18d1855479233f9f66074',
    messagingSenderId: '40178181277',
    projectId: 'ttu-housing-app',
    storageBucket: 'ttu-housing-app.firebasestorage.app',
    iosBundleId: 'com.example.ttuHousingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPyjiPYd0AccpXEYP9uAFwkFhAYu4Vzms',
    appId: '1:40178181277:web:ddcf8d828ce18122f66074',
    messagingSenderId: '40178181277',
    projectId: 'ttu-housing-app',
    authDomain: 'ttu-housing-app.firebaseapp.com',
    storageBucket: 'ttu-housing-app.firebasestorage.app',
    measurementId: 'G-7WQYG00679',
  );

}